name: Code Quality Check

on:
  push:
    branches:
      - CICD/-MKDIR-and-YML-files  
      - main
      - CICD-test-py
  pull_request:
    branches:
      - CICD/-MKDIR-and-YML-files 
      - main
      - CICD-test-py


jobs:
  lint_and_security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit safety
        pip install pytest
        pip install -r requirements.txt

    - name: Run PEP 8 compliance check (flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics

    - name: Run security check (bandit)
      run: |
        bandit . -s B108

    - name: Run dependency vulnerability check (safety)
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
        args: >
          safety check --full-report
          -i 71591,70612,70212

    - name: Test with pytest
      run: |
          pytest
