name: Code Quality Check

on:
  push:
    branches:
      - CICD/-MKDIR-and-YML-files  
      - main
      - CICD-test-py
  pull_request:
    branches:
      - CICD/-MKDIR-and-YML-files 
      - main
      - CICD-test-py


jobs:
  lint_and_security:
    runs-on: ubuntu-latest
    steps:
    - name: Set pythonpath
      run: echo "PYTHONPATH=$(pwd)/python/lambda1:$(pwd)/python/lambda1/src" >> "$GITHUB_ENV"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit
        pip install pytest
        pip install -r requirements.txt

    - name: Run PEP 8 compliance check (flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics

    - name: Run security check (bandit)
      run: |
        bandit . -s B108

    - name: AWS Creds
      uses: aws-actions/configure-aws-credentials@v4
      
      with:
        audience: sts.amazonaws.com
        aws-region: eu-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_SECRET }}
        
    - name: Set pythonpath
      run: echo "PYTHONPATH=$(pwd)/python/lambda1:$(pwd)/python/lambda1/src" >> "$GITHUB_ENV"
      
    - name: Test with pytest
      run: |
          echo $PYTHONPATH
          pytest

  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: requirements.txt
