name: Database Integration Tests

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow from the Actions tab in GitHub.


jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run database integration tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pytest tests/integration --database-url=${{ secrets.DATABASE_URL }}